### ISSUE TITLE
重名

### ISSUE THREAD

**Issue by undefined-ux** [i-l-2018/2-dongxiaotian-683#1]
你好作者，我们重名了，希望能认识一下您！

**Comment by chineselaugh** [comment]
你是14级的嘛？
我之前好像见过

---原始邮件---
发件人: "董晓天"<notifications@github.com&gt;
发送时间: 2020年3月12日(周四) 下午3:31
收件人: "i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [i-l-2018/2-dongxiaotian-683] 重名 (#1)




 
你好作者，我们重名了，希望能认识一下您！

**Comment by undefined-ux** [comment]
您好，我跟您应该不是一级的，我现在还是一个初三学生


dongxiaotian123456@outlook.com
 
发件人： 董笑田
发送时间： 2020-03-15 01:41
收件人： i-l-2018/2-dongxiaotian-683
抄送： 董晓天; Author
主题： Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)
你是14级的嘛？ 
我之前好像见过 

---原始邮件--- 
发件人: "董晓天"<notifications@github.com&gt; 
发送时间: 2020年3月12日(周四) 下午3:31 
收件人: "i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [i-l-2018/2-dongxiaotian-683] 重名 (#1) 





你好作者，我们重名了，希望能认识一下您！

**Comment by chineselaugh** [comment]
哈哈哈，那你用git是来做什么呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"董晓天"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月15日(星期天) 下午5:49
收件人:&nbsp;"i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&gt;;
抄送:&nbsp;"莫林"<604138336@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)





 
 您好，我跟您应该不是一级的，我现在还是一个初三学生 
 
 
 dongxiaotian123456@outlook.com 
   
 发件人： 董笑田 
 发送时间： 2020-03-15 01:41 
 收件人： i-l-2018/2-dongxiaotian-683 
 抄送： 董晓天; Author 
 主题： Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1) 
 你是14级的嘛？  
 我之前好像见过  
 
 ---原始邮件---  
 发件人: "董晓天"<notifications@github.com&amp;gt;  
 发送时间: 2020年3月12日(周四) 下午3:31  
 收件人: "i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&amp;gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;;  
 主题: [i-l-2018/2-dongxiaotian-683] 重名 (#1)  
 
 
 
 
 
 你好作者，我们重名了，希望能认识一下您！

**Comment by undefined-ux** [comment]
我在学写python，现在在用Git是为了方便自己返回上一次修改


dongxiaotian123456@outlook.com
 
发件人： 董笑田
发送时间： 2020-03-15 18:02
收件人： i-l-2018/2-dongxiaotian-683
抄送： 董晓天; Author
主题： Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)
哈哈哈，那你用git是来做什么呢？ 




------------------&nbsp;原始邮件&nbsp;------------------ 
发件人:&nbsp;"董晓天"<notifications@github.com&gt;; 
发送时间:&nbsp;2020年3月15日(星期天) 下午5:49 
收件人:&nbsp;"i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&gt;; 
抄送:&nbsp;"莫林"<604138336@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
主题:&nbsp;Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1) 






您好，我跟您应该不是一级的，我现在还是一个初三学生 


dongxiaotian123456@outlook.com 

发件人： 董笑田 
发送时间： 2020-03-15 01:41 
收件人： i-l-2018/2-dongxiaotian-683 
抄送： 董晓天; Author 
主题： Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1) 
你是14级的嘛？ 
我之前好像见过 

---原始邮件--- 
发件人: "董晓天"<notifications@github.com&amp;gt; 
发送时间: 2020年3月12日(周四) 下午3:31 
收件人: "i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&amp;gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
主题: [i-l-2018/2-dongxiaotian-683] 重名 (#1) 





你好作者，我们重名了，希望能认识一下您！ 

― 
You are receiving this because you are subscribed to this thread. 
Reply to this email directly, view it on GitHub, or unsubscribe. 
― 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub, or unsubscribe. 

― 
You are receiving this because you commented. 
Reply to this email directly, view it on GitHub, or unsubscribe. 
―

**Comment by chineselaugh** [comment]
那你一定是南方人，哈哈哈，初三，挺好哦，加油！要不断学习啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"董晓天"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 上午6:40
收件人:&nbsp;"i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&gt;;
抄送:&nbsp;"莫林"<604138336@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)





 
 我在学写python，现在在用Git是为了方便自己返回上一次修改 
 
 
 dongxiaotian123456@outlook.com 
   
 发件人： 董笑田 
 发送时间： 2020-03-15 18:02 
 收件人： i-l-2018/2-dongxiaotian-683 
 抄送： 董晓天; Author 
 主题： Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1) 
 哈哈哈，那你用git是来做什么呢？  
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------  
 发件人:&amp;nbsp;"董晓天"<notifications@github.com&amp;gt;;  
 发送时间:&amp;nbsp;2020年3月15日(星期天) 下午5:49  
 收件人:&amp;nbsp;"i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&amp;gt;;  
 抄送:&amp;nbsp;"莫林"<604138336@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;  
 主题:&amp;nbsp;Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)  
 
 
 
 
 
 
 您好，我跟您应该不是一级的，我现在还是一个初三学生  
 
 
 dongxiaotian123456@outlook.com  
 
 发件人： 董笑田  
 发送时间： 2020-03-15 01:41  
 收件人： i-l-2018/2-dongxiaotian-683  
 抄送： 董晓天; Author  
 主题： Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)  
 你是14级的嘛？  
 我之前好像见过  
 
 ---原始邮件---  
 发件人: "董晓天"<notifications@github.com&amp;amp;gt;  
 发送时间: 2020年3月12日(周四) 下午3:31  
 收件人: "i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&amp;amp;gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
 主题: [i-l-2018/2-dongxiaotian-683] 重名 (#1)  
 
 
 
 
 
 你好作者，我们重名了，希望能认识一下您！  
 
 ―  
 You are receiving this because you are subscribed to this thread.  
 Reply to this email directly, view it on GitHub, or unsubscribe.  
 ―  
 You are receiving this because you authored the thread.  
 Reply to this email directly, view it on GitHub, or unsubscribe.  
 
 ―  
 You are receiving this because you commented.  
 Reply to this email directly, view it on GitHub, or unsubscribe.  
 ―

**Comment by undefined-ux** [comment]
其实我是北方人，我家在山东。
________________________________
发件人: 董笑田 <notifications@github.com>
发送时间: 2020年3月17日 0:25
收件人: i-l-2018/2-dongxiaotian-683 <2-dongxiaotian-683@noreply.github.com>
抄送: 董晓天 <dongxiaotian123456@outlook.com>; Author <author@noreply.github.com>
主题: Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)


那你一定是南方人，哈哈哈，初三，挺好哦，加油！要不断学习啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"董晓天"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 上午6:40
收件人:&nbsp;"i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&gt;;
抄送:&nbsp;"莫林"<604138336@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)






我在学写python，现在在用Git是为了方便自己返回上一次修改


dongxiaotian123456@outlook.com

发件人： 董笑田
发送时间： 2020-03-15 18:02
收件人： i-l-2018/2-dongxiaotian-683
抄送： 董晓天; Author
主题： Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)
哈哈哈，那你用git是来做什么呢？




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"董晓天"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年3月15日(星期天) 下午5:49
收件人:&amp;nbsp;"i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"莫林"<604138336@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)






您好，我跟您应该不是一级的，我现在还是一个初三学生


dongxiaotian123456@outlook.com

发件人： 董笑田
发送时间： 2020-03-15 01:41
收件人： i-l-2018/2-dongxiaotian-683
抄送： 董晓天; Author
主题： Re: [i-l-2018/2-dongxiaotian-683] 重名 (#1)
你是14级的嘛？
我之前好像见过

---原始邮件---
发件人: "董晓天"<notifications@github.com&amp;amp;gt;
发送时间: 2020年3月12日(周四) 下午3:31
收件人: "i-l-2018/2-dongxiaotian-683"<2-dongxiaotian-683@noreply.github.com&amp;amp;gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;
主题: [i-l-2018/2-dongxiaotian-683] 重名 (#1)





你好作者，我们重名了，希望能认识一下您！

D
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
D
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

D
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
D
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

―
